public class Shining {
    public static void main(String[] args) {
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
        grinder();
    }
    
    public static void grinder() {
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");
        System.out.println("All work and no play makes Jack a dull boy");

    }
}